version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: ai-crm-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev

  # Add more services as needed (e.g., database, cache, etc.)
  # Example:
  # db:
  #   image: postgres:15-alpine
  #   container_name: ai-crm-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=ai_crm
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: 